#!/bin/bash
echo "Automatisch systeemherstel"                                                                                      
echo "=========================="                                                                                      
echo "(C) PindaNet.be, Brugge, Dany Pinoy, `date -r /livemnt/boot/autorun +'%d %B %Y'`"                                              
                                                            
echo                                                                                                                   
echo "Dit is experimentele software.                                                                                 
Het gebruik ervan is geheel voor eigen risico.                                                                                       
PindaNet.be en openSUSE e.v. aanvaarden geen enkele aansprakelijkheid voor                                                           
schade aan hard- en software, verloren gegane data of andere direct of                                                               
indirect door het gebruik van deze software ontstane schade.                                                                         
In sommige landen kunnen de gebruikte software en andere componenten aan                                                             
exportregelingen of patenten gebonden zijn.                                                                                          
In deze landen mag deze software niet verspreid worden zoals dat normaal bij
software onder de gpl-licentie gebruikelijk is.
Als u het met deze condities niet eens bent, mag u deze software niet
gebruiken."
echo
while true; do
  echo
  echo 'Typ een opdracht (restore, halt, reboot, terminal, backup): '
  read keuze
  case "$keuze" in
    "restore")  mount /livemnt/boot -o rw,remount
      echo
      echo 'Welke backup terugzetten (child, parent, grandparent): '
      read keuze
      case "$keuze" in
        "parent") zcat /livemnt/boot/parent.linux.partclone.gz | partclone.restore --output /dev/sda3;;
        "grandparent") zcat /livemnt/boot/grandparent.linux.partclone.gz | partclone.restore --output /dev/sda3;;
        *) zcat /livemnt/boot/child.linux.partclone.gz | partclone.restore --output /dev/sda3;;
      esac;;
    "halt")  echo "De computer wordt automatisch afgesloten."
      echo "U hoeft enkel te wachten..............."
      shutdown -h now
      sleep 3000;;
    "reboot")   echo "De computer wordt automatisch herstart."
      echo "U hoeft enkel te wachten..............."
      shutdown -r now
      sleep 3000;;
    "terminal") break;;
    "backup") mount /livemnt/boot -o rw,remount
      rm /livemnt/boot/grandparent.linux.partclone.gz
      mv /livemnt/boot/parent.linux.partclone.gz /livemnt/boot/grandparent.linux.partclone.gz
      mv /livemnt/boot/child.linux.partclone.gz /livemnt/boot/parent.linux.partclone.gz
      partclone.extfs --clone --source /dev/sda3 | gzip -c > /livemnt/boot/child.linux.partclone.gz;;
  esac
done
