#!/bin/bash
function fout {
	printf "\n\033[1;31;40m %s. Computer NIET uitschakelen. Verwittig de systeembeheerder." "$1"
	read line
	exit
}
echo Welkom bij het PindaNet SNT Backupsysteem
if [ "`grep restorewindows /proc/cmdline`" ]; then
        gunzip -c /livemnt/boot/windows.img.gz | ntfsclone --restore-image --overwrite /dev/sda4 -
        if [ $? -ne 0 ]; then
        	fout "Herstellen Windows mislukt"
        fi
        shutdown -h now
fi
read -s -p "Backupwachtwoord: " wachtwoord
echo
if [ $wachtwoord == "sntlcvo" ]; then
        mount /livemnt/boot -o rw,remount,relatime,data=ordered
        rm /livemnt/boot/windows.parent.img.gz
        mv /livemnt/boot/windows.img.gz /livemnt/boot/windows.parent.img.gz 
        ntfsclone --save-image -o - /dev/sda4 | gzip -c > /livemnt/boot/windows.img.gz
        if [ $? -ne 0 ]; then
        	fout "Windows back-up aanmaken mislukt"
        fi
        shutdown -h now
fi
if [ $wachtwoord == "basis" ]; then
        mount /livemnt/boot -o rw,remount,relatime,data=ordered
        ntfsclone --save-image -o - /dev/sda4 | gzip -c > /livemnt/boot/windows.basis.img.gz
        if [ $? -ne 0 ]; then
        	fout "Windows back-up aanmaken mislukt"
        fi
        shutdown -h now
fi
if [ $wachtwoord == "herstel" ]; then
        gunzip -c /livemnt/boot/windows.basis.img.gz | ntfsclone --restore-image --overwrite /dev/sda4 -
        if [ $? -ne 0 ]; then
        	fout "Herstellen Windows mislukt"
        fi
        shutdown -h now
fi
if [ $wachtwoord == "parent" ]; then
        gunzip -c /livemnt/boot/windows.parent.img.gz | ntfsclone --restore-image --overwrite /dev/sda4 -
        if [ $? -ne 0 ]; then
        	fout "Herstellen Windows mislukt"
        fi
        shutdown -h now
fi
if [ $wachtwoord == "sysrec" ]; then
	exit
fi
printf '\033[1;31;40m Foutief Backupwachtwoord. Computer wordt binnen de minuut afgesloten.'
sleep 60
shutdown -h now
